### ISSUE TITLE
Global list of Tissot ellipses 

### ISSUE THREAD

**Issue by porst17** [danielramosg/sphereofearth#2]
Currently, each map projection shows it's own set of Tissot ellipses. It would be better to have the same set of ellipses or more precisely: the same set of geographical coordinates and radii which then results in different Tissot ellipses in the different projections.

This makes it easy to compare the different projections and is also good for tutors who often switch back and forth between projections during their explanations.

**Comment by porst17** [comment]
I can also think of an additional check box, which sets the set of coordinates globally for all map projections based on the currently selected map projection. This would be like a mix between the current approach and my idea from above.

It has the advantage, that visitors in an exhibitions can still be asked about their opinion how a certain ellipse might look like at a certain position, that has already been shown for another map projection.

Having both local and global behavior to choose from seems to be a good solution from a didactical point of view (IMHO).

**Comment by danielramosg** [comment]
For some time I thought on a single screen with all six maps. Then it would totally make sense to have the same set of ellipses. Furthermore, there would be one real cursor and five ghost cursors on the same coordinates on the other maps. However, I discarded it just because independent maps was simpler. Besides, maps would be too small to fit all six on the screen. Maybe a Mosaic tab with this disposition would be nice, do you think?

Your proposal is simpler, I will make some tests.

**Comment by porst17** [comment]
Would do you mean with mosaic tab? Put all maps side-by-side? Well, they will probably be too small, but you can try if it's not too much work.

The proposal with the additional check box that overwrites the list of ellipses globally is much simpler, yes.

**Comment by danielramosg** [comment]
done in https://github.com/danielramosg/sphereofearth/commit/9be085b1db2bf798fb5fcefbce04cadfeb474e87
still thinking on a mosaic... maybe in a future.
